### ISSUE TITLE
ASE files from the Design language should be mastered here

### ISSUE THREAD

**Issue by mbarlock** [IBM-Design/colors#10]
The ASE files are the "single source of truth" for what the colors should be. We should keep them in a more visible place, Like here!

http://www.ibm.com/design/language/resources

**Comment by mbarlock** [comment]
@hchughes Any huge problems with this?

**Comment by seejamescode** [comment]
The v2.0 branch has this! If somebody can test it, that would be great. @matthewgallo or @mbarlock?

**Comment by mbarlock** [comment]
Which pull request?

**Comment by seejamescode** [comment]
No PR yet. Just in the v2.0 branch for now.

**Comment by seejamescode** [comment]
Closing this because v2.0 resolves it.
