### ISSUE TITLE
White color variants seem to incorrectly use the wrong color scale

### ISSUE THREAD

**Issue by mbarlock** [IBM-Design/colors#11]
The white color values (ie cool-white 40) check in here in the scss mixin and the json file seem to be incorrect given the [color contrast](http://www.ibm.com/design/language/framework/visual/color#contrast) guide as I can put purple-50 text on a cool-white-40 background and its perfectly accessible. I believe these values should actually be `cool-white 4`. As in drop the 0 on the end of all of the numbers.

**Comment by mbarlock** [comment]
@hchughes thoughts? I believe the ASE files have them as `cool-white 4` and not `40`.

**Comment by seejamescode** [comment]
With #10, I hope to close this!

**Comment by seejamescode** [comment]
Closing this because v2.0 resolves it.
