### ISSUE TITLE
Additional formats

### ISSUE THREAD

**Issue by dcwarwick** [IBM-Design/colors#16]
This package currently offers an SCSS file and a JSON file. There are a few more useful formats that clients might use, which could be easily added, potentially including:
* SASS -- the indented syntax versus the CSS extension syntax
* LESS -- Less-CSS, an alternative to SASS which is quite widespread
* JS -- a simple Javascript module yielding the same data as the JSON file contents
* STYL -- Stylus, another alternative to SASS/LESS

**Comment by seejamescode** [comment]
Hi @dcwarwick, thanks for the issue and sorry for such a late reply. New owners are revitalizing activity on the repo now. With the popularity of SCSS and ability to use the .json file in JavaScript, I feel comfortable where we are now in support.

If you feel strong about this still, we would love individual issues and PRs for any you prefer!
