### ISSUE TITLE
Generate dist folder on deployment 

### ISSUE THREAD

**Issue by mbarlock** [IBM-Design/colors#17]
On release, before publishing to bower and npm, generate a dist folder.

**Comment by mbarlock** [comment]
ref #15

I've realized that bower pulls from git. Is there a config from a different branch where we can put the dist folder or do we have to automatically check the dist folder back into master?

**Comment by mbarlock** [comment]
@seejamescode Why did you close this? This is still quite valuable as it generates the .scss and the .json outputs from a single input rather than forcing someone to touch two places in order to make a change. Any time we can remove human error from coding, the better.

**Comment by mbarlock** [comment]
If you don't agree with the method of generation, you should remove the `src` notion from this project and the related gulp tasks.

**Comment by seejamescode** [comment]
The description was not clear for me then. Currently, the source/ code is edited and outputs into the root. Are you suggesting we have the files generated into a dist/ folder also?

**Comment by mbarlock** [comment]
It looks like the code outputs to a dist folder https://github.com/IBM-Design/colors/blob/master/gulpfile.js#L15. I'm suggesting that the dist folder not be checked in and generated at release time

**Comment by seejamescode** [comment]
I gotcha now! I was confused when my example project did not have a manual dist folder.

Do you think the dist folder is right place for output files? I feel like the root would be easier for non-developers.

**Comment by seejamescode** [comment]
Now that I have poked around a bit: I would lean towards using a dist folder, but removing the gitignore for the folder. It would beneficial for all file types to be accessible directly from the repo.  I am reflecting that in PR #24. Thoughts?

**Comment by seejamescode** [comment]
We can keep this discussion going in #26, but I believe the breaking change point and also keeping it non-dev friendly are good reasons to keep built files in the root.
