### ISSUE TITLE
Broken links for the License text

### ISSUE THREAD

**Issue by priyagriddaluru** [IBM-Design/colors#21]
Hello,
I am looking for the license text for this open source package at "https://github.com/IBM-Design/colors/blob/master/LICENSE.md"  which has links to following URLs. But both the links are broken.
http://www.ibm.com/design/language/resources.shtml
http://www.ibm.com/design/language/legal/download-agreement.shtml

I am seeing the following errors when I access those urls :
"Oops — that's not right!
Sorry, unless you really were hoping to find our 404 message, the page you were looking for has been moved or deleted"

Can someone please help fix these links?
Thank you!
Priya

**Comment by seejamescode** [comment]
Hi Priya! Thanks for noticing this and sorry for such a late reply. We are currently switching to new repo owners.

For the license, it looks like it is the same as our icons repo (here)[https://github.com/IBM-Design/icons/blob/master/LICENSE.md]. However, I will double-check this week and update this repo appropriately.

**Comment by matthewgallo** [comment]
Just to add on to this, we're planning on adding the legal page specified above (http://www.ibm.com/design/language/legal/download-agreement), along with others back in to the IBM Design Language very shortly.

**Comment by matthewgallo** [comment]
The download agreement legal page can now be seen here:
http://www.ibm.com/design/language/legal/download-agreement/
