### ISSUE TITLE
Organization of .ase

### ISSUE THREAD

**Issue by derrickligon** [IBM-Design/colors#28]
The new .ase doesn't have each color group in its own folder which makes it difficult to read through/use the palette as effectively as before.

<img width="586" alt="new-palette-on-right" src="https://cloud.githubusercontent.com/assets/23021094/20316102/24024288-ab26-11e6-8744-fbaefe0bf151.png">

**Comment by seejamescode** [comment]
The one on the left was organized because it was manually made. I will take a look if we can implement the grouping in our automated process!
