### ISSUE TITLE
Green 40 is the wrong hex value 

### ISSUE THREAD

**Issue by mbarlock** [IBM-Design/colors#3]
currently green40 is #6eb400 but on https://www.ibm.com/design/language/resources/swatch-book.shtml its 5AA700

**Comment by mbarlock** [comment]
While fixing this I found that orange 10, and cool-gray 60 and 80 are also wrong

**Comment by shagadorn** [comment]
Green 40 should be #5AA700.
Orange 10 is correct in the git, the swatch book is wrong. it should be #ffd4a0 
Cool-grey 60 is wrong everywhere. it should be #5a6464
Cool-grey 80, the git is correct and the swatchbook is wrong. it should be #323c3c

**Comment by mbarlock** [comment]
Updated pr #4 to reflect this..
