### ISSUE TITLE
v2.0 requires two gulps

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/colors#33]
For the v2.0 branch, we have to run gulp twice to get a `ibm-colors.sketchpalette` or rely on an old version of `./ibm-colors.json`. Even though the gulp task `sketchpalette` is dependent on gulp task `partials`, the task does not wait for `./ibm-colors.json` to be built.

If anyone can work on this, please let me know!

**Comment by chrisdhanaraj** [comment]
@seejamescode you need to return the gulp streams in order for gulp to know that a task is finished. 

i.e, instead of

```js
gulp.task('sketchpalette', [ 'partials' ], function () {
  gulp.src("./ibm-colors.json")...
```

it should be

```js
gulp.task('sketchpalette', [ 'partials' ], function () {
  return gulp.src("./ibm-colors.json")...
```

Do that for each of your tasks and it'll probs resolve the issue.

**Comment by seejamescode** [comment]
That makes since and I did so. I am still getting the same behavior though.

**Comment by ind1go** [comment]
I made a PR for this - it was just a case of fixing some incorrect dependency orderings in the end (though aided by the above work to return the stream in each of the tasks).

**Comment by seejamescode** [comment]
Thanks @ind1go!
