### ISSUE TITLE
v2.0 "cool blue" is warmer than "warm blue"

### ISSUE THREAD

**Issue by shagadorn** [IBM-Design/colors#36]
should these names be switched?

![screen shot 2016-11-28 at 2 55 40 pm](https://cloud.githubusercontent.com/assets/6225214/20686001/6b063e9a-b57c-11e6-8a2c-b5c003795b5c.png)

**Comment by jordaniusrex** [comment]
@shagadorn It seems like there are opposing, widely-held interpretations of what makes blue warmer or cooler. I found [this explanation from Sharon Hicks](http://sharonhicksfineart.com/blog/57475/warm-or-cool-ultramarine-blue-vs-thalo-blue-) pretty convincing, but maybe we should consider alternative nomenclature to prevent any potential confusion.

**Comment by hchughes** [comment]
The names have now been changed. "Renamed “Warm Blue” to “Cerulean” and “Cool Blue” to “Ultramarine” to prevent confusion about different interpretations of nomenclature.
