### ISSUE TITLE
Generate .clr in sRGB Color Profile

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/colors#40]
@ind1go says this is the current gulp flow:
```
       .--> scss
json --+--> ase --+--> clr
                  '--> sketchpalette
```

When the .ase file is created, anything coming from it is using Adobe/Generic RGB. The .clr file should stick to sRGB instead. This means we should not generate the .clr file from the .ase. The .sketchpalette is still correct.

Is the above correct, @shagadorn?

This is a sequel to #29.

**Comment by shagadorn** [comment]
I don't use the sketchpalette so I'm not sure on that. But yes to everything else.

**Comment by ind1go** [comment]
Nice work on fixing this! Out of interest, what's the `color-tool` utility you used?

**Comment by seejamescode** [comment]
https://github.com/ramonpoca/ColorTools
