### ISSUE TITLE
Prefer `0` to `1` for color swatches

### ISSUE THREAD

**Issue by joshblack** [IBM-Design/colors#42]
Not sure what the standard is, but when consuming the colors from a design perspective the lightest colors have typically been referred to as the `0` version of that color, versus `1` which is the current naming scheme in v2.0. Would love to know if `1` is the official name for that variation of the colors, and to see if there was any chance we could move to `0` if so. Thanks!

**Comment by seejamescode** [comment]
Hey buddy! Yeah, the "1"s will be official when v2 is released. It was discovered that a good amount of 0s did not pass contrast accessibility tests when placed on 50s grades. The switch to 1s is to represent when this is true and obey the IDL 50-point contrast rule. I'll miss the clean 10-point intervals also! And I'll be sure to include this reasoning in the release notes too.
