### ISSUE TITLE
Remove Eyeglass version warning

### ISSUE THREAD

**Issue by cuyaproductions** [IBM-Design/colors#56]
I get this error when I use the latest version of Eyeglass:
```
The following modules are incompatible with eyeglass 1.2.1:
  ibm-colors needed eyeglass ^0.8.3
```

I think this has to do with the `needs` property in the `package.json` in this module, but I'm not familiar with Eyeglass to know if that's true.

**Comment by ind1go** [comment]
Suggest this may be one for @Snugug - I'm not familiar enough with Eyeglass to know the repercussions of upping the requirement, or if there's a better semver we should specify.

**Comment by Snugug** [comment]
Can up to semver ^1.0 without concern
