### ISSUE TITLE
Color Blind safe Orange 40 does not match result of color("orange", 40)

### ISSUE THREAD

**Issue by bwilty** [IBM-Design/colors#59]
I think this _may_ be an error in the documentation here https://www.ibm.com/design/language/resources/color-library/, so please close this issue and point me in the right direction if this is the wrong medium to report this error.

On the website, the "Color blind safe" version of Orange 40 is #fe6100.  However, regular Orange 40 is #db7c00.  The sass function color("orange", 40) returns #db7c00, which is valid for one of the Orange 40's but not the other.

**Comment by seejamescode** [comment]
Thanks for the catch, @bwilty. It looks like it is supposed to be Peach 40. Issue has been opened on the Language repo if you have access: https://github.ibm.com/Design/ibm-design-language/issues/475
