### ISSUE TITLE
Single source values

### ISSUE THREAD

**Issue by kevinSuttle** [IBM-Design/colors#6]
https://github.com/IBM-Design/colors/blob/master/_ibm-colors.scss#L159 vs 
https://github.com/IBM-Design/colors/blob/master/ibm-colors.json

http://stackoverflow.com/a/26702092/398574

Great example here: https://github.com/zaim/webcolors/

**Comment by kevinSuttle** [comment]
There are even multiple definitions of the entire color palette in the site HTML itself.

**Comment by dcwarwick** [comment]
This is a really good point, and would make the package more robust. Also, I think we should add more formats than just SCSS -- I've had several people ask about LESS, for example -- but we should fix a single source before we proliferate the values any further.

I've run up a template script that will do this. Let me tidy it up a bit, and test it out, and I'll submit it as a pull request.
