### ISSUE TITLE
Install options question

### ISSUE THREAD

**Issue by dalemanthei** [IBM-Design/colors#64]
The instructions call for this to be installed with `npm install ibm-design-colors --save`

I'm wondering if `--save-dev` isn't the more appropriate option?

**Comment by seejamescode** [comment]
Thanks for the attention, @dalemanthei. If the developer does not have a build process, `--save` is the best option for them. Placing this package as a DevDependency will stop it from being installed during uploads to hosting solutions like IBM Bluemix.

We hope that those with a build process will know about `--save-dev`, but feel free to make a documentation pull request to clarify.
